# Servlet Container & Health Setup
server:
  address: 0.0.0.0
management:
  address: 0.0.0.0
  port: 8081
endpoints:
  enabled: false
  health:
    enabled: true
    
# Spring Boot
spring:

# Camel Spring Boot
camel:
  component:
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
  springboot:
    name: camel-springboot-rabbitmq

# Logging
logging:
  config: classpath:logback.xml
  level:
    #org.apache.camel: DEBUG
